# -*- coding: utf-8 -*-
"""신입생세미나과제.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OAXi4Aa0gc74abS8pa9T8nhX1s0hp2Ai
"""

import matplotlib.pyplot as plt
import numpy as np

def water_capacity(heights):
    if not heights:
        return 0

    left = 0
    right = len(heights) - 1
    max_left = max_right = 0
    water_capacity = 0

    while left < right:
        if heights[left] < heights[right]:
            if heights[left] >= max_left:
                max_left = heights[left]
            else:
                water_capacity += max_left - heights[left]
            left += 1
        else:
            if heights[right] >= max_right:
                max_right = heights[right]
            else:
                water_capacity += max_right - heights[right]
            right -= 1

    return water_capacity

# 예시 입력과 출력
print(water_capacity([0,1,0,2,1,0,1,3,2,1,2,1]))  # 출력: 6
print(water_capacity([1,0,1,2,0,2]))  # 출력: 3
print(water_capacity([2,0,2,1,0,1,1,1,3]))  # 출력: 8

def max_water_capacity(heights):
    if not heights:
        return 0

    left = 0
    right = len(heights) - 1
    max_left = max_right = 0
    water_capacity = 0
    water_levels = [0] * len(heights)

    while left < right:
        if heights[left] < heights[right]:
            if heights[left] >= max_left:
                max_left = heights[left]
            else:
                water_capacity += max_left - heights[left]
                water_levels[left] = max_left - heights[left]
            left += 1
        else:
            if heights[right] >= max_right:
                max_right = heights[right]
            else:
                water_capacity += max_right - heights[right]
                water_levels[right] = max_right - heights[right]
            right -= 1

    return water_capacity, water_levels

def plot_water_levels(heights):
    water_capacity, water_levels = max_water_capacity(heights)
    x = list(range(len(heights)))
    n = len(heights)

    fig, ax = plt.subplots(figsize=(n/3, n/3))
    ax.bar(x, heights, color='lightgray', label='Height', width=1)
    ax.bar(x, water_levels, bottom = heights, color='blue', alpha=0.5, label='Water Capacity', width=1)
    ax.set_aspect('equal')
    ax.set_xticklabels([])
    ax.set_yticks(np.arange(0, max(heights) + 2, 1))  # y축의 눈금 변경
    ax.set_ylim(0, max(heights) + 1)  # y축의 범위 설정
    plt.show()

# 예시 입력과 출력
print(max_water_capacity([0,1,0,2,1,0,1,3,2,1,2,1])[0])  # 출력: 6
print(max_water_capacity([4,2,0,3,2,5])[0])  # 출력: 9
print(max_water_capacity([3,1,2,4,0,1,3,2])[0])  # 출력: 8

# 예시 입력에 대한 시각화
plot_water_levels([0,1,0,2,1,0,1,3,2,1,2,1])
plot_water_levels([4,2,0,3,2,5])
plot_water_levels([3,1,2,4,0,1,3,2])